zcash/halo2

- src/arithmetic.rs
- src/plonk.rs
- src/plonk/verifier.rs
- src/poly.rs
- src/poly/commitment.rs
- src/poly/commitment/verifier.rs
> Support batching and accumulation in polynomial opening argument

- src/plonk.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
- src/poly/commitment/verifier.rs
> Incorporate MSM/Guard into PLONK verifier API and arithmetic

- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
> Support for auxiliary advice wires

- src/plonk.rs
- src/plonk/prover.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
> Rename `OpeningProof` to just `Proof`.

- Contributor_Agreement
The current Contributor Agreement is missing a few sections and the section numbering is off.
> Update Contributor Agreement

- src/plonk.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
- src/transcript.rs
> Make transcript generic over curve point

- Cargo.toml
- benches/plonk.rs
- examples/performance_model.rs
- src/lib.rs
- src/model.rs
- src/plonk/prover.rs
- src/poly/commitment.rs
- src/poly/commitment/msm.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/domain.rs
Also adds metrics collection for performance modelling.
Part of #47.
> PLONK benchmarks

- Cargo.toml
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly.rs
> Small optimisations

- Cargo.toml
- benches/arithmetic.rs
- benches/plonk.rs
- examples/performance_model.rs
- src/arithmetic.rs
- src/arithmetic/curves.rs
- src/arithmetic/fields.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/domain.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
- src/transcript.rs
- src/tweedle/curves.rs
- src/tweedle/fields.rs
- src/tweedle/fields/fp.rs
- src/tweedle/fields/fq.rs
The `Field` trait in this crate is now `FieldExt: ff::PrimeField`.
> Migrate to ff traits

- Cargo.toml
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/lookup.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
> Lookup argument implementation

- src/plonk.rs
- src/plonk/prover.rs
- src/plonk/vanishing.rs
- src/plonk/vanishing/prover.rs
- src/plonk/vanishing/verifier.rs
- src/plonk/verifier.rs
> Vanishing argument

- .github/workflows/book.yml
- .github/workflows/ci.yml
- book/book.toml
- book/src/SUMMARY.md
- book/src/user.md
- book/src/user/lookup-tables.md
- book/src/user/simple-example.md
- book/src/user/tips-and-tricks.md
`mdbook build book` will still work locally after this, but won't render LaTeX equations by default. `cargo install mdbook-katex` to render them.
> More book bits

- Cargo.toml
- src/model.rs
- src/poly/commitment.rs
- src/poly/commitment/msm.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/domain.rs
Fixes CI breakage caused by the latest metrics alpha release.
> Bump metrics crate and pin its dependencies

- book/book.toml
- book/src/SUMMARY.md
- book/src/design.md
- book/src/design/lookup-argument.md
> book: Add design page for lookup argument

- .gitignore
- book/Makefile
- book/edithtml.sh
- book/src/SUMMARY.md
- book/src/concepts.md
- book/src/concepts/arithmetization.md
- book/src/concepts/background.md
- book/src/concepts/chips.md
- book/src/concepts/cores.md
- book/src/concepts/gadgets.md
- book/src/concepts/proofs.md
> [book] Write Concepts section

- .github/workflows/book.yml
- .github/workflows/ci.yml
https://blog.rust-lang.org/2021/01/04/mdbook-security-advisory.html
> Use mdbook 0.4.5

- src/circuit.rs
- src/circuit/layouter.rs
- src/gadget.rs
- src/lib.rs
Also includes a simple single-chip layouter that we can use to develop chips.
> Circuit component traits

- book/src/design/gadgets/sha256/table16.md
> [Book] Fix W numbering in SHA-256 table16 doc.

- src/plonk/permutation/prover.rs
- src/poly/multiopen/prover.rs
I missed these after I rebased/merged #140.
> More clippy lint fixes

- .github/ISSUE_TEMPLATE/eli15.md
- book/src/background.md
This will hopefully encourage readers to submit feedback as they read the book, enabling us to catch things that could be explained better.
> Add an issue template for improving the Halo 2 book

- benches/plonk.rs
- examples/performance_model.rs
- src/dev.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/lookup.rs
- src/plonk/permutation.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
> Multi-proof prover

- benches/plonk.rs
- examples/performance_model.rs
- src/plonk.rs
- src/poly/commitment.rs
- src/poly/multiopen.rs
- src/transcript.rs
> Replace DummyHash with BLAKE2b

- Cargo.toml
- src/plonk/lookup/prover.rs
See https://github.com/myrrlyn/funty/issues/3
> Downgrade to funty 1.1.0 to fix CI

- src/gadget.rs
- src/gadget/sha256.rs
This adds the Init-Update-Finalize gadget struct, and the trait defining the instructions it requires.
> SHA-256 gadget

- benches/plonk.rs
- examples/circuit-layout.rs
- examples/performance_model.rs
- examples/simple-example.rs
- src/circuit.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/permutation.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
> Allow permutations to be over all column types

- src/dev.rs
- src/plonk/circuit.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly/domain.rs
This is based on #176 which is currently unmerged.
> Add Expression::Constant variant

- examples/circuit-layout.rs
- src/dev.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/lookup.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly.rs
- src/poly/domain.rs
> Generalise lookup argument to work over expressions

- book/src/concepts/arithmetization.md
- book/src/concepts/cores.md
- book/src/concepts/proofs.md
- book/src/design/proving-system.md
- book/src/design/proving-system/circuit-commitments.md
- book/src/design/proving-system/lookup.md
- book/src/design/proving-system/permutation.md
- book/src/user/tips-and-tricks.md
* Generalize input columns to expressions in lookup argument;
* Cosmetics, minor corrections and wording improvements;
* Improve the section that explains the permutation argument.
> Book improvements

- Cargo.toml
- benches/hashtocurve.rs
- src/arithmetic.rs
- src/arithmetic/curves.rs
- src/arithmetic/fields.rs
- src/arithmetic/hashtocurve.rs
- src/pasta.rs
- src/pasta/curves.rs
- src/pasta/fields/fp.rs
- src/pasta/fields/fq.rs
- src/pasta/hashtocurve.rs
- src/pasta/pallas.rs
- src/pasta/vesta.rs
Add an implementation of simplified SWU. refs zcash/zcash#4710
This builds on sqrt_ratio added in #120.
It should match the Sage implementation at https://github.com/zcash/pasta/blob/master/hashtocurve.sage .
> Hash to curve

- Cargo.toml
- benches/hashtocurve.rs
- examples/performance_model.rs
- src/arithmetic.rs
- src/arithmetic/curves.rs
- src/pasta.rs
- src/pasta/curves.rs
- src/pasta/hashtocurve.rs
- src/pasta/pallas.rs
- src/pasta/vesta.rs
- src/plonk.rs
- src/plonk/keygen.rs
- src/plonk/lookup/prover.rs
- src/plonk/permutation/keygen.rs
- src/plonk/permutation/prover.rs
- src/plonk/prover.rs
- src/plonk/vanishing/prover.rs
- src/poly/commitment.rs
- src/poly/commitment/msm.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/transcript.rs
> Migrate to group traits

- src/gadget/sha256.rs
I had this done locally, but hadn't quite finished refactoring the `sha-256` branch to separate it out before #166 was merged.
> Alter the SHA-256 gadget to require namespacing

- README.md
> Add documentation of Minimum Supported Rust Version.

- benches/plonk.rs
- examples/circuit-layout.rs
- examples/performance_model.rs
- examples/simple-example.rs
- src/circuit.rs
- src/circuit/layouter.rs
- src/dev.rs
- src/dev/graph.rs
- src/dev/graph/layout.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
> Upstream Permutation struct into plonk::circuit

- examples/simple-example.rs
- src/plonk/circuit.rs
This currently just wraps a `Column<Fixed>`, but enables us to start writing circuits that can later have their selector usage optimised.
Part of #116.
> Add a Selector type

- examples/sha256/benches.rs
- examples/sha256/main.rs
- examples/sha256/table16.rs
- examples/sha256/table16/compression.rs
- examples/sha256/table16/compression/compression_gates.rs
- examples/sha256/table16/compression/compression_util.rs
- examples/sha256/table16/compression/subregion_digest.rs
- examples/sha256/table16/compression/subregion_initial.rs
- examples/sha256/table16/compression/subregion_main.rs
- examples/sha256/table16/message_schedule.rs
- examples/sha256/table16/message_schedule/schedule_gates.rs
- examples/sha256/table16/message_schedule/schedule_util.rs
- examples/sha256/table16/message_schedule/subregion1.rs
- examples/sha256/table16/message_schedule/subregion2.rs
- examples/sha256/table16/message_schedule/subregion3.rs
- examples/sha256/table16/spread_table.rs
- src/circuit.rs
To test: `cargo test --example sha256`
This is based on the new `Config` abstraction #238 (which is currently unmerged)
> Fix SHA256 example

- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
Best reviewed hiding whitespace changes.
> MockProver: Return all constraint failures, not just first

- benches/plonk.rs
- examples/sha256/benches.rs
- src/plonk.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/prover.rs
- src/plonk/vanishing/prover.rs
- src/plonk/vanishing/verifier.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
- src/transcript.rs
- tests/plonk_api.rs
> Add support for full-field challenge space

- benches/plonk.rs
- examples/circuit-layout.rs
- examples/sha256/main.rs
- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
- src/plonk/circuit.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- tests/plonk_api.rs
This enables a gate such as ECC complete addition to define its constraints in terms of a common set of queried columns.
> Allow multiple polynomial constraints per gate

- src/arithmetic.rs
Document that batch inversion leaves zero as zero.
> Document that batch inversion in arithmetic.rs leaves zero as zero

- src/plonk/circuit.rs
Co-authored-by: Jack Grigg <jack@electriccoin.co>
> plonk::circuit.rs: Add Expression::square() method.

- examples/circuit-layout.rs
- src/dev.rs
- src/dev/graph/layout.rs
This makes it easier to add configuration to the renderer.
Best reviewed with whitespace changes hidden.
> dev: CircuitLayout builder

- src/dev.rs
Current layouters measure the shape of regions by looking at the cells
they assign. If a chip developer forgets to assign a cell in a region,
it is possible for active gates to "stick out" past the edge of a
measured region shape.
`MockProver` checks that all active gates have their cells assigned,
but this was previously checked globally. If a layouter happened to
position the buggy region such that the dangling gate overlapped an
assigned cell in in adjacent region, this check would pass.
In this commit, we extend the check to be per-region. We map enabled
selectors and assigned cells to a specific region, and then if a gate
is active within a region, we require that its cells be assigned within
that same region.
Closes zcash/halo2#297.
> MockProver: Check cell assignment per-region instead of globally

- src/circuit.rs
- src/circuit/layouter.rs
- src/circuit/layouter/single_pass.rs
- src/circuit/layouter/v1.rs
We aren't using anything in `FieldExt` at these layers.
> Reduce various trait requirements from `FieldExt` to `Field`

- src/dev.rs
- src/plonk/lookup/prover.rs
- src/plonk/prover.rs
- src/plonk/vanishing/prover.rs
- src/plonk/verifier.rs
- src/poly/commitment/msm.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen/prover.rs
Remove needless `.collect()`s and borrows.
> Make this crate clippy clean for warnings on nightly

- Cargo.toml
- README.md
- src/arithmetic.rs
- src/lib.rs
- src/multicore.rs
> Use a rayon ThreadPool

- examples/simple-example.rs
- src/circuit.rs
- src/circuit/floor_planner/single_pass.rs
- src/circuit/floor_planner/v1.rs
- src/circuit/floor_planner/v1/strategy.rs
- src/circuit/layouter.rs
- src/dev.rs
- src/dev/graph.rs
- src/dev/graph/layout.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- tests/plonk_api.rs
> Add `Region::assign_advice_from_constant` API

- src/dev/graph/layout.rs
- src/plonk/circuit.rs
> Change canonical column ordering to Instance < Advice < Fixed

- src/circuit/floor_planner/single_pass.rs
The previous behaviour assumed that all regions were always assigned
in increasing start-row order. That assumption is broken in e.g. the
Merkle path tests, which position two Sinsemilla calls in parallel.
The layouter was working fine for current tests, but in an adjacent
PR that changed the Merkle path chip's behaviour, it started to
produce invalid circuits.
The new behaviour emulates the `floor_planner::V1` behaviour in an
(intentionally) inefficient way: constants are positioned immediately
after the regions they are assigned to, in the first constants column.
If that column is also used in regions, those regions will now be
positioned without overlapping any assigned global constants.
Co-authored-by: therealyingtong <yingtong@z.cash>
> Fix SimpleFloorPlanner's handling of global constants

- src/dev.rs
- src/dev/cost.rs
- src/dev/gates.rs
- src/dev/graph/layout.rs
- `CircuitGates` tooling for printing circuit gate details
- `CircuitCost::marginal_proof_size` API
- Improvements to `CircuitLayout`
> Developer tooling improvements

- book/src/background/fields.md
> [book] Update link `upa.md` -> `plonkish.md`

- book/src/user/dev-tools.md
- examples/circuit-layout.rs
> Update `dev-graph` examples

- book/src/concepts/chips.md
- book/src/concepts/gadgets.md
These were missed in zcash/halo2#320.
> book: Rename remaining UPA references to PLONKish

- CHANGELOG.md
- Cargo.toml
- src/dev.rs
- src/dev/graph/layout.rs
- src/plonk/error.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- tests/plonk_api.rs
> Improve error message when `k` is too small

- src/dev.rs
- src/dev/gates.rs
- src/dev/metadata.rs
- src/dev/util.rs
- src/plonk/circuit.rs
This collects and provides values for non-selector queries.
Closes zcash/halo2#364.
> dev: Collect values of queried cells for unsatisfied constraints

- src/poly/multiopen.rs
> multiopen: Replace test_coherence with proptest.

- examples/sha256/benches.rs
- examples/sha256/main.rs
- examples/sha256/table16.rs
- examples/sha256/table16/compression.rs
- examples/sha256/table16/compression/compression_gates.rs
- examples/sha256/table16/compression/compression_util.rs
- examples/sha256/table16/compression/subregion_digest.rs
- examples/sha256/table16/compression/subregion_initial.rs
- examples/sha256/table16/compression/subregion_main.rs
- examples/sha256/table16/gates.rs
- examples/sha256/table16/message_schedule.rs
- examples/sha256/table16/message_schedule/schedule_gates.rs
- examples/sha256/table16/message_schedule/schedule_util.rs
- examples/sha256/table16/message_schedule/subregion1.rs
- examples/sha256/table16/message_schedule/subregion2.rs
- examples/sha256/table16/message_schedule/subregion3.rs
- examples/sha256/table16/spread_table.rs
- examples/sha256/table16/util.rs
- src/plonk/circuit.rs
Closes #390. Based on #383.   
Run `cargo test --example sha256` to test.
> Update sha256 example to work with new API

- .github/workflows/bench.yml
- Cargo.toml
- benches/plonk.rs
> CI: Benchmark tweaks

- halo2_proofs/src/poly/evaluator.rs
Also includes a fix for `impl Debug for poly::Ast` which was never usable with typical evaluators.
> Fix handling of short chunks in `poly::Evaluator`

- COPYING
- README.md
- halo2/CHANGELOG.md
- halo2/Cargo.toml
- halo2_gadgets/CHANGELOG.md
- halo2_gadgets/Cargo.toml
- halo2_gadgets/README.md
- halo2_proofs/CHANGELOG.md
- halo2_proofs/Cargo.toml
- halo2_proofs/README.md
> `halo2 0.1.0-beta.2` etc.

- book/src/design/protocol.md
Co-authored-by: Daira Hopwood <daira@jacaranda.org>
> [book] Correct typo in Q_0 of protocol description.

- halo2_gadgets/CHANGELOG.md
- halo2_gadgets/Cargo.toml
- halo2_proofs/CHANGELOG.md
- halo2_proofs/Cargo.toml
> Release `halo2_proofs 0.1.0-beta.3`

- halo2_gadgets/CHANGELOG.md
- halo2_gadgets/Cargo.toml
- halo2_proofs/CHANGELOG.md
- halo2_proofs/Cargo.toml
> Release halo2_proofs 0.1.0-beta.4

- book/src/SUMMARY.md
- book/src/design/implementation/selector-combining.md
> [book] Add description of selector combining optimization

- book/macros.txt
- book/src/SUMMARY.md
- book/src/design/protocol.md
This doesn't need any code review as it just touches the book.
> Add draft of halo2 proofs to the formal protocol description in book

- halo2_gadgets/CHANGELOG.md
- halo2_gadgets/src/ecc.rs
- halo2_gadgets/src/ecc/chip.rs
- halo2_gadgets/src/ecc/chip/mul.rs
> [ECC gadget] Distinguish base field element case in variable-base scalar mul.

- book/src/SUMMARY.md
This was added in https://github.com/zcash/halo2/pull/551 but may have been undone somewhere.
> [book] Add 'Selector combining' to SUMMARY.md

- book/src/SUMMARY.md
- book/src/design/gadgets/endoscaling.md
refs #583
Co-authored-by: Ying Tong Lai <yingtong@electriccoin.co>
> Add description of endoscaling and public input handling

- halo2_proofs/src/plonk/lookup/verifier.rs
> There is no z' in the lookup argument, only z

- .github/workflows/ci.yml
- book/src/SUMMARY.md
- book/src/dev.md
- book/src/dev/features.md
- halo2_gadgets/Cargo.toml
- halo2_gadgets/src/lib.rs
- halo2_proofs/Cargo.toml
> Add harness for `nightly -> beta -> stable` dev workflow

- halo2_gadgets/src/ecc/chip/mul_fixed.rs
- halo2_gadgets/src/poseidon/pow5.rs
- halo2_gadgets/src/sinsemilla/chip.rs
- halo2_gadgets/src/sinsemilla/chip/generator_table.rs
- halo2_proofs/CHANGELOG.md
- halo2_proofs/benches/plonk.rs
- halo2_proofs/examples/circuit-layout.rs
- halo2_proofs/src/plonk/circuit.rs
- halo2_proofs/src/plonk/permutation/verifier.rs
- halo2_proofs/tests/plonk_api.rs
> Only allow fixed queries at `Rotation::cur`

- book/src/user/wasm-port.md
> Update the status of support for nested web workers in Safari

- halo2_gadgets/benches/sha256.rs
Fixing small bugs that prevented the benchmark of SHA256
> Sha256 update

- halo2_proofs/src/circuit/value.rs
- halo2_proofs/src/dev.rs
- halo2_proofs/src/dev/tfp.rs
> Create a `TracingFloorPlanner` for debugging purposes

- halo2_proofs/src/dev.rs
Fixes https://github.com/zcash/halo2/issues/725
> docs(halo2_proofs): Improve MockProver::verify description
