- src/plonk/prover.rs
- src/poly.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
Add loop in PLONK prover to repeatedly call `OpeningProof::create()`, each time incrementing blinding factor `f_blind`, until correct value is sampled.
Closes #8
> Remove fork hack from OpeningProof::create()

- src/plonk.rs
- src/plonk/prover.rs
- src/poly/commitment.rs
- src/poly/commitment/verifier.rs
This makes it so that the G element in the accumulator actually contains an H term from the parameters, which means we can make it so that aux wires in PLONK also contain this blind. This is to be consistent with fixed wires, which we "faux blind" to avoid points at infinity during recursive verification.
Closes #25
> Faux blinded accumulator

- Cargo.toml
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
The `Column` struct is generic over any type which implements the `ColumnType` trait.
The `ColumnType` trait is implemented for `Advice`, `Fixed`, and `Aux` structs, and the `Any` enum (which has `Advice`, `Fixed`, `Aux` variants).
> Introduce Column struct and ColumnType trait

- .github/workflows/ci.yml
- Cargo.toml
- src/lib.rs
- src/model.rs
We don't need to commit to an MSRV yet, and this avoids the problem
where some of our in-flux dependencies bump their MSRV (or don't have
a defined MSRV and make changes to use more recent features) causing
our CI to break.
> Use latest stable Rust

- src/arithmetic.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/permutation.rs
- src/plonk/permutation/keygen.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
- src/transcript.rs
> Extract permutation argument and introduce typed challenges

- .github/workflows/ci.yml
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/vanishing/verifier.rs
- src/poly/commitment/prover.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
Previously, `ChallengeScalar` could use the operator traits defined on
the `F: Field` type it wrapped, due to its `impl Deref<Target = F>`.
This was technically ambiguous, and Rust 1.49.0 makes that ambiguity an
error.
We could fix this by adding operator impls with `ChallengeScalar` on the
RHS, but that would conflict with zcash/halo2#111. Instead we manually
dereference every challenge scalar when used in an arithmetic operation.
> Fix breakage of trait resolution in Rust 1.49.0

- src/arithmetic/fields.rs
- src/pasta/fields.rs
- src/pasta/fields/fp.rs
- src/pasta/fields/fq.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/transcript.rs
**The base of this branch is currently `transcript-api-2` which is [unmerged](https://github.com/zcash/halo2/pull/111).**
This modifies the scheme to be almost identical to the construction outlined in Appendix A.2 of "Proof-Carrying Data from Accumulation Schemes" (https://eprint.iacr.org/2020/499). The only remaining difference is that we do not compute `[v] U = [v] [z] U` but instead subtract `[v] G_0` from the commitment before opening which I figure will be more efficient in the circuit.
As a consequence of this, things are a little simpler and we can remove both
* transcript forking
* deterministic square root computation
as I don't forsee us needing either of these.
> Avoid square challenges in inner product argument

- Cargo.toml
- benches/arithmetic.rs
- benches/plonk.rs
- examples/performance_model.rs
- src/arithmetic/curves.rs
- src/arithmetic/fields.rs
- src/pasta/curves.rs
- src/pasta/fields.rs
- src/pasta/fields/fp.rs
- src/pasta/fields/fq.rs
- src/plonk.rs
- src/plonk/lookup.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/permutation.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/prover.rs
- src/plonk/vanishing.rs
- src/plonk/vanishing/prover.rs
- src/plonk/vanishing/verifier.rs
- src/plonk/verifier.rs
- src/poly/commitment.rs
- src/poly/commitment/msm.rs
- src/poly/commitment/prover.rs
- src/poly/commitment/verifier.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
- src/transcript.rs
Closes #66.
The goal of this PR is to solve multiple problems:
1. Currently, we have various `Proof` objects scattered around the codebase for each of the different subprotocols. Some of these proof objects contain vectors of (vectors of) curve points and scalars. This complicates serialization/deserialization of proofs because the lengths of these vectors depend on the configuration of the circuit. We don't want to encode the lengths of vectors inside of proofs because we'll know them at runtime and they do not change. We should instead treat proof objects as opaque byte streams into the verifier.
2. It's easy to accidentally put stuff in a `Proof` object that isn't also placed in the transcript.
3. In #67 we need to be able to create multiple PLONK proofs at the same time and they will …
> New Transcript API (and modified commitment scheme)

- src/plonk/lookup/prover.rs
- src/plonk/permutation/prover.rs
- src/plonk/prover.rs
- src/plonk/vanishing/prover.rs
- src/poly/multiopen.rs
- src/poly/multiopen/prover.rs
- src/poly/multiopen/verifier.rs
The Lagrange interpolation we were doing was pointless. kate_division sheds the constant term off each time it is invoked because the quotient polynomial isn't affected by it. This means we were modifying coefficients that end up getting discarded anyway; the quotient polynomial coefficients are already determined exactly by the leading coefficients and the fact that a root exists at each of the points.
This has some other consequences for the PLONK code that no longer needs to keep track of the evals after they end up in the transcript.
> Remove eval from ProverQuery in multiopen

- book/src/concepts/arithmetization.md
- book/src/concepts/proofs.md
> Make terminology more consistent with the ZKProof reference and Sean's usage

- benches/plonk.rs
- examples/performance_model.rs
- src/dev.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/permutation/keygen.rs
- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/poly.rs
- src/poly/domain.rs
The first commit of this branch just removes the unused `rotations` field from ConstraintSystem.
The second commit switches to using Rotation in the circuit interface rather than i32; it can be dropped if folks don't care for it.
> Remove rotations from ConstraintSystem & use Rotation instead of i32 for circuit methods.

- CHANGELOG.md
Adds a base structure to the changelog. Once the first release has been cut, we can start tracking changes using the [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) format. For an example of this format in action, see https://github.com/str4d/rage/blob/master/age/CHANGELOG.md
> Initialize the changelog

- Cargo.toml
- src/arithmetic/fields.rs
- src/pasta/fields/fp.rs
- src/pasta/fields/fq.rs
- src/poly/commitment.rs
Based on [[Sarkar2020]](https://eprint.iacr.org/2020/1407) and [[BDLSY2012]](https://cr.yp.to/papers.html#ed25519).
The API is also based on https://ristretto.group/formulas/invsqrt.html . fixes zcash/halo2#72
Co-authored-by: Jack Grigg <jack@electriccoin.co>
> Add sqrt_ratio implementation.

- src/circuit.rs
- src/circuit/layouter.rs
- src/plonk/circuit.rs
We implement the simplest approach here: position the region starting at the earliest row for which none of the columns are in use.
> Simple layouter strategy to track column usage

- Cargo.toml
- benches/plonk.rs
- examples/circuit-layout.rs
- examples/performance_model.rs
- src/circuit.rs
- src/circuit/layouter.rs
- src/dev.rs
- src/dev/graph.rs
- src/dev/graph/layout.rs
- src/lib.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
This adds support for:
- Gate naming
- User namespacing of gadgets
- As-implemented, I think this also can just keep on namespacing through into instructions until a region boundary, which may or may not be desirable.
- Gadget name extraction (behind the `gadget-traces` feature flag)
- Region naming
- Cell annotations
- Developer tooling to:
- render a circuit's namespace as a dot graph.
- render a circuit as a table.
Closes #124.
Part of #157.
> Circuit annotations and developer tooling

- book/src/concepts/arithmetization.md
- book/src/concepts/chips.md
- book/src/design/proving-system/circuit-commitments.md
- book/src/design/proving-system/comparison.md
- examples/circuit-layout.rs
- examples/performance_model.rs
- examples/simple-example.rs
- src/dev.rs
- src/dev/graph/layout.rs
- src/plonk.rs
- src/plonk/circuit.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
> Rename "auxiliary column" to "instance column" in the book and in code

- examples/simple-example.rs
- src/circuit.rs
- src/circuit/layouter.rs
- src/gadget/ecc.rs
Provide access to general chip state loaded at the beginning of circuit synthesis.
> Store `Loaded` chip state in chip

- src/pasta/curves.rs
Prime-order groups can be treated as a group with a cofactor of 1,
allowing them to be used in cofactor-aware protocols like RedDSA.
> impl group::cofactor::CofactorGroup for Pallas and Vesta

- src/arithmetic/curves.rs
- src/pasta/curves.rs
Also removes the unused `CurveAffine::from_bytes_wide` and `CurveAffine::to_bytes_wide` methods.
> Fix Group::random implementation for Pallas and Vesta

- LICENSE-BOSL
We're in process of renaming TGPPL to BOSL. This PR adds the licence text. Forthcoming PRs will change TGPPL references to BOSL throughout the various repos.
> Adding the Bootstrap Open Source Licence

- .github/workflows/ci.yml
- .github/workflows/lints-beta.yml
- .github/workflows/lints-stable.yml
We move Clippy lints into separate workflows that only run either directly on branches, or on trial-merges of PRs, to deduplicate the
lint annotations. We will still see stable lints duplicated in beta, but that's fine.
> CI: Reduce noise of clippy lints

- Cargo.toml
- book/src/SUMMARY.md
- book/src/user/dev-tools.md
- examples/cost-model.rs
Usage: `cargo run --example cost-model -- --help`
Closes #47.
> examples: Add cost model

- src/dev.rs
The `MockProver` should handle query rotations for lookups, like the real prover does (https://github.com/zcash/halo2/blob/main/src/plonk/lookup/prover.rs#L100)
> [MockProver] Handle query rotations in lookups

- examples/sha256/benches.rs
- examples/sha256/main.rs
- examples/sha256/table16.rs
- examples/sha256/table16/compression.rs
- examples/sha256/table16/compression/compression_util.rs
- examples/sha256/table16/compression/subregion_digest.rs
- examples/sha256/table16/compression/subregion_initial.rs
- examples/sha256/table16/compression/subregion_main.rs
- examples/sha256/table16/message_schedule.rs
- examples/sha256/table16/message_schedule/schedule_util.rs
- examples/sha256/table16/message_schedule/subregion1.rs
- examples/sha256/table16/message_schedule/subregion2.rs
- examples/sha256/table16/message_schedule/subregion3.rs
- examples/sha256/table16/spread_table.rs
Split out from #253 to reduce the diff.
To test: `cargo test --example sha256 --all-features`
> Fix `sha256` example for new config abstraction

- .github/workflows/book.yml
`mdbook-katex` is installed from crates.io, and if it doesn't use the same version of `mdbook` it can cause build issues.
> CI: Build book with latest mdbook

- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
- src/plonk/circuit.rs
The closure passed to `ConstraintSystem::create_gate` can now return:
- Tuples of `(&'static str, Expression<F>)`
- Anything implementing `IntoIterator` (e.g. `Some(Expression<F>)`)
> Enable annotating individual constraints within gates

- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
- src/plonk/circuit.rs
Enabling selectors to be used in gates at non-zero rotations leads to
confusing gates, and inhibits our ability to create visualizations of
circuits. In most cases, a gate can be rearranged so that the selectors
have no rotation; in cases where cross-gate selector optimisations are
required, these can still be implemented using fixed columns.
> Remove rotations from Selectors

- src/circuit.rs
- src/circuit/layouter.rs
- src/circuit/layouter/single_pass.rs
- src/circuit/layouter/v1.rs
- src/dev.rs
- src/dev/graph.rs
- src/dev/graph/layout.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- src/poly.rs
- src/poly/domain.rs
Value closures passed to `assign_advice` and `assign_fixed` can now return a `(numerator, denominator)` tuple, in order to defer inversions until after assignment.
> Add support for batched inversion of cell assignments

- benches/plonk.rs
- examples/circuit-layout.rs
- tests/plonk_api.rs
These were all early examples that used the `Circuit` trait without any layouter, which is incompatible with upcoming changes.
The minimal change to the `PinnedVerificationKey` is because the lookup table is being allocated at the top of its columns instead of in-place.
> Migrate PLONK-gate-using circuits to use SingleChipLayouter

- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
- src/dev/metadata.rs
This is a step towards making the metadata more reusable and developer-friendly.
> dev: Refactor VerifyFailure to extract metadata structs

- book/src/design/implementation/fields.md
As noted in the NCC audit:
Some formulas in the explanation of Sarkar's square root referenced the value g<sup>2<sup>-24</sup></sup>, where g is a primitive 2<sup>32</sup>-th root of unity modulo p (or q). This value is not defined, since g has order 2<sup>32</sup>, and 2<sup>24</sup> is not invertible modulo 2<sup>32</sup>. This expression has been corrected to g<sup>-2<sup>24</sup></sup>.
> [book] Fix Sarkar square root explanation

- src/dev.rs
Circuit developers need to use selectors (or equivalent) to prevent their
custom gates from being active on unusable rows. By marking the advice
cells in these rows as "poisoned" and tracking this through expressions,
we can provide a better error message to developers that indicates the
missing selector issue.
Closes zcash/halo2#329.
> MockProver: Poison unusable advice cells

- src/dev/graph/layout.rs
This makes it easier to see how the global permutation argument is being used, and also enables us to hunt for missing equality constraints.
> dev: Enable visualizing equality constraints in circuit layouts

- src/plonk/permutation/prover.rs
- src/plonk/permutation/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
The permutation argument has some fixed polynomials (which define the permutation) that are evaluated at `x`. Right now the code evaluates them for every argument, but the evaluations do not vary across circuit instances. Similarly to how we merge fixed evaluations across circuit instances, we do the same with these permutation polynomial openings.
This reduces the proof size and proving time.
> Merge the common pieces of the permutation argument into a separate proof component

- src/dev.rs
- src/dev/cost.rs
- tests/plonk_api.rs
This adds the logic to collect the various contributions to the proof size. They can be viewed in the `Debug` impl of `ProofSize`.
Part of #339.
> dev: Add CircuitCost tool with proof size measurement

- benches/plonk.rs
- examples/circuit-layout.rs
- examples/simple-example.rs
- examples/two-chip.rs
- src/dev.rs
- src/plonk/circuit.rs
- src/plonk/circuit/compress_selectors.rs
- src/plonk/lookup/prover.rs
- src/plonk/lookup/verifier.rs
- src/plonk/prover.rs
- src/plonk/verifier.rs
- src/poly.rs
- tests/plonk_api.rs
Previously, we were storing negations as "scaled by -1", which meant we needed to evaluate them with multiplications instead of cheaper negations or additions.
> `Expression::Negated`

- examples/circuit-layout.rs
- src/circuit.rs
- src/circuit/floor_planner/single_pass.rs
- src/circuit/floor_planner/v1.rs
- src/circuit/layouter.rs
- src/dev.rs
- src/dev/cost.rs
- src/dev/graph.rs
- src/dev/graph/layout.rs
- src/plonk/circuit.rs
- src/plonk/keygen.rs
- src/plonk/prover.rs
- tests/plonk_api.rs
The new API correctly handles lookup table assignments; in particular, layouters now ensure that every column used in a table has a valid table entry on every usable row.
> Add a `Layouter::assign_table` API

- book/src/user/dev-tools.md
Currently on the bottom of the dev-tools HTML page[0] we can see HTML
tags being rendered inside the code tag.
This commit should stop html tags appearing inside the `<code>` tags, and
allow for proper printing of the book.
[0] https://zcash.github.io/halo2/user/dev-tools.html
> book: Fix rendering of cost-model output.

- CHANGELOG.md
- Cargo.toml
- README.md
This is the beta version of `halo2` used on testnet in zcashd v4.5.0.
> halo2 0.1.0-beta.1

- CHANGELOG.md
- src/arithmetic.rs
- src/dev.rs
- src/helpers.rs
- src/lib.rs
- src/plonk.rs
- src/plonk/lookup/prover.rs
- src/plonk/permutation.rs
- src/plonk/permutation/prover.rs
- src/poly.rs
- src/poly/commitment.rs
- src/poly/commitment/verifier.rs
- src/poly/domain.rs
- src/transcript.rs
- tests/plonk_api.rs
This removes our dependence on several `FieldExt` and `CurveAffine` methods, preparing us for their removal from `pasta_curves`.
> Clean up our trait usage

- src/plonk/error.rs
- src/plonk/permutation/keygen.rs
Closes #384. 
This is raised when a copy constraint involves a column that has
not been included in the permutation.
> Introduce plonk::Error::ColumnNotInPermutation error.

- benches/plonk.rs
- examples/circuit-layout.rs
- examples/simple-example.rs
- examples/two-chip.rs
- src/circuit.rs
- src/plonk/circuit.rs
- tests/plonk_api.rs
Addresses https://github.com/zcash/halo2/issues/288.
> circuit.rs: Introduce `AssignedCell` struct.

- examples/sha256/table16.rs
- examples/sha256/table16/message_schedule/subregion2.rs
- examples/sha256/table16/message_schedule/subregion3.rs
zcash/halo2#337 had been updated to account for `AssignedCell`, before
the change to simplify its bounds was made. `AssignedCell` now requires
the `From` impls to take `&VR`.
> sha256: Fix `AssignedCell` `From` impls for `AssignedBits` and `Bits`

- .github/workflows/bench.yml
The workflow will comment on commits that cause a performance regression
of at least 200% (e.g. proving taking twice as long); we'll tune this as
we figure out how well benchmarking works on standard GitHub builders.
Part of zcash/halo2#419.
> CI: Add benchmarks workflow

- src/plonk/error.rs
When a user forgets to add `meta.enable_equalty` on the columns to enforce copy constraints, it was hard for the user to find out the root cause of the error. The issue was reported in #384 and later fixed in #385.
#385 introduced a new error message `ColumnNotInPermutation` to isolate this particular error from the other `Synthesis` error. We could improve further by hinting the user how to fix it correctly.
Hint user to apply `meta.enable_equalty` on the column.
> improve error message on ColumnNotInPermutation

- CHANGELOG.md
- benches/plonk.rs
- examples/circuit-layout.rs
- examples/sha256/table16.rs
- examples/simple-example.rs
- examples/two-chip.rs
- src/plonk/circuit.rs
- src/plonk/permutation.rs
- tests/plonk_api.rs
As suggested by daira in #345, it's sometimes annoying to call `.into()`
for all of the columns in methods like `enable_equality`.
Specially when you end up with situations where you have `&Column<_>` where you are forced to do something like:
`meta.enable_equality((*column).into())`
This change changes the public API methods that require `Column<Any>`
by `<C: Into<Column<Any>> + Copy>` which removes the need to call `.into()` on the public API and it's called inside of the functions that accept this
parameters.
The `Copy` is added since `Into` consumes the Column, and sometimes we
fall into the situation of needing to clone when we can simply require
the copy and avoid more code verbosity.
Resolves: #345
> Change to `Into<Column<Any>>` for pub API methods

- CHANGELOG.md
- src/dev.rs
Previously, we only reported the absolute row on which a failure occurred; this is unhelpful when an optimising floor planner is in use. Now, if the lookup failure overlaps a region, we report that instead.
> Improve `dev::VerifyFailure::Lookup` information

- CHANGELOG.md
- src/dev.rs
> Rename `VerifyFailure::Cell` to `VerifyFailure::CellNotAssigned`

- src/dev.rs
This fills the unused rows of a table column with its default value in the `MockProver`.
Review this commit-by-commit, checking that the `bad_lookup` test:
- passes in the first commit (wrong behaviour),
- fails in the second commit (expected behaviour), and
- passes in the last commit after being fixed.
> [dev] Implement `Assignment::fill_from_row()` for `MockProver`.

- CHANGELOG.md
- src/dev.rs
- src/dev/metadata.rs
> dev: Enable `VerifyFailure::ConstraintNotSatisfied` to point to region offsets

- halo2_proofs/CHANGELOG.md
- halo2_proofs/benches/plonk.rs
- halo2_proofs/src/plonk/verifier.rs
- halo2_proofs/src/poly/multiopen.rs
- halo2_proofs/src/poly/multiopen/verifier.rs
- halo2_proofs/tests/plonk_api.rs
Previously `plonk::verify_proof` took an `MSM` as an argument, to enable
batch verification. However, this also required that it take a source of
randomness in order to enforce separation of proofs within a batch. This
made single-proof verification unnecessarily non-deterministic.
We now have a `VerificationStrategy` trait encapsulating the necessary
details, and separate `SingleVerifier` and `BatchVerifier` structs for
the specific variants. Proof verifiers no longer need to create and
manage the `MSM` themselves, and single-proof verifiers no longer need
to supply a source of randomness.
Co-authored-by: Sean Bowe <sean@electriccoin.co>
> halo2_proofs: Improve `plonk::verify_proof` API

- halo2_gadgets/Cargo.toml
- halo2_gadgets/src/ecc/chip/mul.rs
- halo2_gadgets/src/utilities.rs
> halo2_gadgets: Migrate from bigint to uint

- .github/workflows/book.yml
`cargo rustdoc` only works for a single package. To render docs for
a workspace while passing config options to `rustdoc`, we need to use
the `RUSTDOCFLAGS` environment variable.
We also add several other flags to handle the switch to `cargo doc`:
- `--no-deps` ensures we only build packages in the workspace.
- `--enable-index-page` (unstable) adds a landing page showing the list
of rendered crate docs.
> CI: Fix rustdoc rendering to handle workspace

- .github/workflows/book.yml
We require nightly Rust to build the documentation, but latest nightly
has a bug where `--no-deps` causes an ICE.
> CI: Pin nightly version in book workflow

- book/src/design/protocol.md
- halo2_proofs/src/poly/commitment.rs
- halo2_proofs/src/poly/commitment/msm.rs
- halo2_proofs/src/poly/commitment/prover.rs
- halo2_proofs/src/poly/commitment/verifier.rs
- halo2_proofs/src/poly/multiopen/prover.rs
- halo2_proofs/src/poly/multiopen/verifier.rs
This changes variable names in the multiopen and commitment opening implementations
and the book's protocol description to keep names and indicies consistent with one
another.
Co-Authored-By: Jack Grigg <jack@electriccoin.co>
> halo2_proofs: rename variables for consistency

- book/src/design/gadgets/ecc/addition.md
* use biimplication in the correctness argument to ensure both soundness and completeness;
* avoid introducing lambda at all; it's unnecessary and omitting it shortens the explanation.
Co-authored-by: Jack Grigg <str4d@electriccoin.co>
> Improve the explanation of incomplete addition

- halo2_proofs/src/circuit.rs
- halo2_proofs/src/plonk/assigned.rs
This PR adds various usability methods to `Assigned<F: Field>`, to make it easier to use in contexts where `F: Field` was previously used.
Closes zcash/halo2#425.
> Expand `Assigned<F>` APIs

- halo2_proofs/CHANGELOG.md
- halo2_proofs/src/plonk/vanishing/prover.rs
- halo2_proofs/src/poly/evaluator.rs
The existing code will fold together a very deep AST that applies Horner's
rule to each gate in a proof -- which could include multiple circuits and
so for some applications will quickly grow such that when we recursively
descend later during evaluation the stack will easily overflow.
This change special cases the application of Horner's rule to a
"DistributePowers" AST node to keep the tree depth from exploding in size.
Closes #536
> Reduce depth of AST by special casing the application of Horner's rule

- halo2_proofs/examples/cost-model.rs
> cost-model.rs: Correct lookup required degree calculation.

- halo2_proofs/Cargo.toml
- halo2_proofs/benches/dev_lookup.rs
Closes #528.
When run on top of #445, we see performance improvements of about 65%:
```
dev-lookup/14           time:   [4.8397 ms 5.0149 ms 5.3867 ms]                          
change: [-61.752% -60.165% -58.040%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 10 measurements (20.00%)
2 (20.00%) high severe
dev-lookup/15           time:   [8.3559 ms 8.4126 ms 8.5434 ms]                         
change: [-66.010% -65.394% -64.644%] (p = 0.00 < 0.05)
Performance has improved.
dev-lookup/16           time:   [17.002 ms 17.195 ms 17.332 ms]                         
change: [-66.549% -66.182% -65.789%] (p = 0.00 < 0.05)
Performance has improved.
dev-lookup/17           time:   [33.441 ms 35.614 ms 38.032 ms]                         
change: [-66.653% -65.223% -63.606%] (p …
```
> Bench heavily padded lookup in MockProver.

- halo2_proofs/src/dev.rs
> Fix mock prover performance regression for lookup arguments

- halo2_gadgets/src/sha256/table16/compression/compression_gates.rs
- halo2_proofs/CHANGELOG.md
- halo2_proofs/src/plonk/circuit.rs
There are two existing patterns for constructing a gate from a set of
constraints with a common selector:
- Create an iterator of constraints, where each constraint includes the
selector:
```
vec![
("foo", selector.clone() * foo),
("bar", selector.clone() * bar),
("baz", selector * bar),
]
```
This requires the user to write O(n) `selector.clone()` calls.
- Create an iterator of constraints, and then map the selector in:
```
vec![
("foo", foo),
("bar", bar),
("baz", bar),
].into_iter().map(move |(name, poly)| (name, selector.clone() * poly))
```
This looks cleaner overall, but the API is not as intuitive, and it
is messier when the constraints are named.
The `Constraints` struct provides a third, clearer API:
```
Constraints::with_selector(
selector,
vec![
("foo", foo),
("bar", bar), …
```
> Add a `Constraints` helper

- .github/workflows/book.yml
The header was moved to fix docs.rs deployment, but the CI workflow wasn't updated to account for this.
> CI: Pass the correct `katex-header.html` path to rustdoc

- halo2_gadgets/src/ecc/chip/add.rs
- halo2_gadgets/src/ecc/chip/add_incomplete.rs
- halo2_gadgets/src/ecc/chip/mul.rs
- halo2_gadgets/src/ecc/chip/mul/complete.rs
- halo2_gadgets/src/ecc/chip/mul/incomplete.rs
- halo2_gadgets/src/ecc/chip/mul/overflow.rs
- halo2_gadgets/src/ecc/chip/mul_fixed.rs
- halo2_gadgets/src/ecc/chip/mul_fixed/base_field_elem.rs
- halo2_gadgets/src/ecc/chip/mul_fixed/full_width.rs
- halo2_gadgets/src/ecc/chip/mul_fixed/short.rs
- halo2_gadgets/src/ecc/chip/witness_point.rs
- halo2_gadgets/src/poseidon/pow5.rs
- halo2_gadgets/src/sinsemilla/chip.rs
- halo2_gadgets/src/sinsemilla/merkle/chip.rs
- halo2_gadgets/src/utilities.rs
- halo2_gadgets/src/utilities/cond_swap.rs
- halo2_gadgets/src/utilities/decompose_running_sum.rs
- halo2_gadgets/src/utilities/lookup_range_check.rs
Only one gate couldn't be migrated without altering the Orchard circuit.
> halo2_gadgets: Migrate chip gates to `Constraints::with_selector`

- halo2/Cargo.toml
See 55364f0d998b5752b9edfbafb5847b8d3306e3fb for why this is necessary.
> halo2: Disable default benchmark harness

- halo2_gadgets/CHANGELOG.md
- halo2_gadgets/src/sinsemilla.rs
- halo2_gadgets/src/utilities.rs
- halo2_gadgets/src/utilities/lookup_range_check.rs
Part of https://github.com/zcash/orchard/issues/83.
> Changes from Orchard circuit review

- halo2_proofs/src/arithmetic.rs
Hi there.
I optimized `best_fft` algorithm and replaced with more efficient `rayon` method.
`n` = 2^k
To precompute the `twiddle factors`, reuse them and it reduced `n` times multiplication.
Prepare specific case when twiddle factor = 1.
To avoid unnecessary `twiddle factor * element` and it reduced `2n` times multiplication.
It slowed down when I implement it as `if` condition so I hardcode that case.
Replace `scope` with `par_iter`.
The official document says that the `par_iter` is the most efficient basically.
https://docs.rs/rayon/latest/rayon/#how-to-use-rayon
I benched them and the speed is the `scope > par_iter > join` but the `join` uses a lot of memory.
https://github.com/appliedzkp/halo2/pull/55#issue-1195660345
Avoid `unshuffle` and multiple times bit reverse, it reduced `n` …
> Optimize Fft

- halo2_proofs/src/poly/commitment/msm.rs
* This removes the `parallelize` calls from inside the MSM when operating on scalars, which has enormous overhead even for relatively large circuits.
* We also now deduplicate the extra bases to minimize the width of the MSM. (Closes #606)
> MSM optimizations

- halo2_proofs/src/poly/evaluator.rs
`poly::Evaluator` stores all of the polynomials registered with it in memory for the duration of its existence. When evaluating an AST, it additionally caches the rotated polynomials in memory, and then chunks all of the rotated polynomials for parallel evaluation.
Previously, it stored a polynomial for every unique AST leaf, regardless of whether that leaf required a rotation or not. This resulted in the unrotated polynomials being stored twice in memory. However, the chunks simply refer to slices over cached polynomials, so we can reference the unrotated polynomials stored in `poly::Evaluator` instead of copies of them stored in the rotated polynomial `HashMap`. This strictly reduces memory usage during proving with no effect on correctness.
> halo2_proofs: Reduce memory usage of `poly::Evaluator`

- halo2_proofs/src/poly.rs
- halo2_proofs/src/poly/domain.rs
- halo2_proofs/src/poly/evaluator.rs
Previously we used the existing `Polynomial::rotate` and `EvaluationDomain::rotate_extended` APIs to rotate the polynomials we query at non-zero rotations, and then stored references to the chunks of each (rotated and unrotated) polynomial as slices. When we reached an `AstLeaf`, we would then clone the corresponding polynomial chunk.
We now avoid all of this with combined "rotate-and-chunk" APIs, making use of the observation that a rotation is simply a renumbering of the indices of the polynomial coefficients. Given that when we reach an `AstLeaf` we already needed to allocate, these new APIs have the same number of allocations during AST evaluation, but enable us to completely avoid caching any information about the rotations or rotated polynomials ahead of time.
> halo2_proofs: Avoid caching rotated polynomials in `poly::Evaluator`

- halo2_proofs/src/plonk/prover.rs
> `plonk::prover::create_proof`: Check that `circuits` and `instances` have equal lengths

- halo2_proofs/src/plonk/circuit.rs
The `TableColumn` should not be used in the `enable_constant` API, since that would introduce global constants not in the logical lookup table. However, there is no reason to disallow copy constraints on already-assigned table cells.
> Allow `enable_equality` on `TableColumn`

- halo2_proofs/src/poly/commitment/verifier.rs
Document that `verify_proof` returns a `Guard` containing an `MSM` that does not include the `[-c]G` term.
> [doc] commitment::verifier: verify_proof does not have [-c]G term

- halo2_proofs/tests/plonk_api.rs
The current working directory for a test always seems to be the root of the crate, hence `./tests/plonk_api_proof.bin` is always the correct path.
> Don't use `include_bytes!` for `plonk_api` test

- halo2_proofs/src/dev.rs
- halo2_proofs/src/dev/failure.rs
- halo2_proofs/src/dev/util.rs
> [MockProver] Check for instance values in gate queries.

- halo2_proofs/CHANGELOG.md
- halo2_proofs/src/circuit/floor_planner/single_pass.rs
- halo2_proofs/src/circuit/floor_planner/v1.rs
- halo2_proofs/src/circuit/layouter.rs
This allows us to access instance column values within a region. Previously, this was done only through `RegionLayouter::assign_advice_from_instance`.
> halo2_proofs: Introduce `RegionLayouter::instance_value` method.

- halo2_proofs/src/plonk/lookup/prover.rs
- halo2_proofs/src/plonk/prover.rs
The `theta` challenge is used in the lookup argument to compress the input and table expressions. This compression can be done fully in the `commit_permuted` step, after which the original uncompressed expressions are no longer needed.
> `lookup::prover`: Compress expressions and cosets in `commit_permuted`

- book/src/user/wasm-port.md
Adds a guide with all the necessary steps it took to get [Zordle](https://github.com/nalinbhardwaj/zordle) shipped to WASM to the halo2 book.
Closes #630.
> WASM Guide

- book/src/design/proving-system/vanishing.md
`(X^n - 1)` is a polynomial instead of a monomial
> fix a typo

- halo2_proofs/Cargo.toml
- halo2_proofs/src/poly/domain.rs
We do not use `EvaluationDomain` with group elements, so there is no need to directly use the FFT `Group` abstraction trait here.
> Simplify `EvaluationDomain` to only accept field elements

- halo2_proofs/src/dev/failure.rs
> [MockProver] failure::FailureLocation: Handle zero-area regions.

- book/book.toml
Resolve #692
Install dependencies:
```bash
pip3 install mdbook-pdf-outline
cargo install mdbook-katex mdbook-pdf
git clone https://github.com/HollowMan6/mdBook
cd mdBook && cargo install --path . --force
```
Ensure chrome / edge is available in your system, then run `mdbook build`.
Generated PDFs:
[book-without-linebreak.pdf](https://github.com/zcash/halo2/files/10310764/book-without-linebreak.pdf)
[book-with-linebreak.pdf](https://github.com/zcash/halo2/files/10310765/book-with-linebreak.pdf)
Signed-off-by: Hollow Man <hollowman@opensuse.org>
> Book PDF generation

- .github/workflows/book.yml
Continuation of #713 
Hi! Sorry I didn't notice that there's a CI for book deploying.
This PR should fix book deploying CI. I've also added the pdf uploading functionality, so that readers now can download the pdf books directly from the GitHub Actions Artifacts.
Signed-off-by: Hollow Man <hollowman@opensuse.org>
> Fix book deploying CI and add pdf uploading

- halo2_gadgets/benches/poseidon.rs
Noticed a small lingering todo in `halo2_gadgets/benches/poseidon.rs` to move the outputs from a `Value` to an instance column. This PR does just that ! 
Resolves #711
> chore: instance columns for poseidon bench

- halo2_gadgets/src/poseidon/primitives/mds.rs
wasm-pack throws an error during compile time when unable to infer the type.
> bug fix - wasm pack compile error

- halo2_gadgets/Cargo.toml
`inferno 0.11.5` raised its MSRV to 1.64.0. Adding this range constraint is fine because it's only a dev-dependency.
> Constrain `inferno` transitive dependency to our MSRV

- README.md
- halo2/Cargo.toml
- halo2_gadgets/Cargo.toml
- halo2_proofs/Cargo.toml
- halo2_proofs/README.md
- halo2_proofs/src/multicore.rs
- halo2_proofs/src/plonk/verifier/batch.rs
Close #648 All test has been passed with/without rayon.
>   Add feature "multicore"  and you can disable rayon by disabling the  "multicore" feature. 

- halo2_proofs/CHANGELOG.md
- halo2_proofs/src/circuit.rs
> halo2_proofs: Add `Region::instance_value`

- halo2_proofs/src/dev/cost.rs
> `dev::cost`: Handle cost calculation for circuits without permutation

- halo2_proofs/CHANGELOG.md
- halo2_proofs/src/plonk/error.rs
This allows us to add new variants in point releases.
> Make `Error` a non_exhaustive type.

- halo2_proofs/src/circuit.rs
- halo2_proofs/src/circuit/floor_planner/single_pass.rs
- halo2_proofs/src/circuit/floor_planner/v1.rs
- halo2_proofs/src/circuit/layouter.rs
- halo2_proofs/src/circuit/table_layouter.rs
- halo2_proofs/src/plonk/circuit.rs
- halo2_proofs/src/plonk/error.rs
"All good lookups are alike, but every bad lookup is bad in its own way" - @nalinbhardwaj
Supersedes #750, inspired by https://github.com/zcash/halo2/pull/750#discussion_r1141000039.
> `plonk::Error::TableError`: Better lookup errors

- book/src/design/protocol.md
I was unable to render the markdown locally, so there might be some errors...
The wording in step one might need some more explanation
Finally as Rasmus pointed out [here](https://github.com/zcash/halo2/pull/777?fbclid=IwAR3-iYgdTQVlz-_ePysX8TRTNMgMkLe6fM_VS2-JoNF6BoVSfmQL0tqoZCI#discussion_r1204307871) there might have been a typo in the last fix so i changed that aswell.
> Patch protocol p poly

- halo2_gadgets/src/poseidon/pow5.rs
Previously, a padding word was first assigned to a fixed column
using `assign_fixed()`, then copied to the `state` advice column using
`copy_advice()`. However, since the prover ignores fixed assignments
during synthesis, the value passed to `copy_advice` is `None`.
This causes the odd-length input to pass the `MockProver`, but fail
in real proof generation with a `Synthesis` error.
> `halo2_gadgets::poseidon`: Fix loading of padding words.
